### ISSUE TITLE
Управление колёсами по отдельности

### ISSUE THREAD

**Issue by Serafimuschka** [Serafimuschka/savoir-faire#3]
## Ты говорил, что при управлении одной осью, обнуляется скорость другой, что исходит из кода:
```cpp
case WHEEL_L:
        thumperTranslate(0xFF, value, 0);
        Serial.print(CMD_SUCCESS);
        break;
    case WHEEL_R:
        thumperTranslate(0xFF, 0, value);
        Serial.print(CMD_SUCCESS);
        break;
    case RWHEEL_L:
        thumperTranslate(0x00, value, 0);
        Serial.print(CMD_SUCCESS);
        break;
    case RWHEEL_R:
        thumperTranslate(0x00, 0, value);
        Serial.print(CMD_SUCCESS);
        break;
    default:
        Serial.print(INVALID_CMD);
        break;
```
***
Собственно, если мы подаём, скажем, пакет `10 FF 19 FF`, то функция должна отправить сначала команды для **передней оси**, затем ждать команды для задней, и выполнять обе команды, пока не поступит сигнал на прерывание. Других решений, не затрагивающих увеличение длины пакета или внедрение дополнительных команд, я не вижу. Поскольку сама функция `thumperTranslate(byte, byte, byte)` способна обработать **всего** *4* состояния из **необходимых** *16*.
### Может стоит расширить первый аргумент до, скажем, `unsigned short`?
В таком случае драйвер "схавает" строго определённое состояние, и обработает его уже сам, исходя из уже имеющихся скоростей. Как я помню, колёса Илона работают именно за счёт разницы в направлениях вращения, а не угловых моментах. Следовательно, скорость можно задать для всего ряда в целом, а не для каждого колеса в отдельности.

**Comment by EuthanasiaTrip** [comment]
В том то и дело, что скорости задаются для всего ряда в целом, т.е. первый аргумент в функции трансляции это для левого ряда, второй - для правого. Насчёт unsigned short немного не понял, в нём будут сразу два значения для направления?

**Comment by Serafimuschka** [comment]
> Насчёт unsigned short немного не понял, в нём будут сразу два значения для направления?

Нет, в нём будет четыре значения: от `0000` до `FFFF`. Каждый байт отвечает за свою ось.

**Comment by EuthanasiaTrip** [comment]
Но функция обработки входящей трансляции с терминала работает только с двумя входящими байтами, т.е. на тампера надо отправлять команду только после того, как все сообщение будет прочитано мегой

**Comment by Serafimuschka** [comment]
Разумеется
